///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ReferenceLine {

  double? x;
  double? y;
  String? id;

  ReferenceLine({
    this.x,
    this.y,
    this.id,
  });
  ReferenceLine.fromJson(Map<String, dynamic> json) {
    x = json['x']?.toDouble();
    y = json['y']?.toDouble();
    id = json['_id']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['x'] = x;
    data['y'] = y;
    data['_id'] = id;
    return data;
  }
}

class WeightLinesPoints {

  double? x;
  double? y;
  String? id;

  WeightLinesPoints({
    this.x,
    this.y,
    this.id,
  });
  WeightLinesPoints.fromJson(Map<String, dynamic> json) {
    x = json['x']?.toDouble();
    y = json['y']?.toDouble();
    id = json['_id']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['x'] = x;
    data['y'] = y;
    data['_id'] = id;
    return data;
  }
}

class WeightLines {

  List<WeightLinesPoints>? points;
  String? id;

  WeightLines({
    this.points,
    this.id,
  });
  WeightLines.fromJson(Map<String, dynamic> json) {
    if (json['points'] != null) {
      final v = json['points'];
      final arr0 = <WeightLinesPoints>[];
      v.forEach((v) {
        arr0.add(WeightLinesPoints.fromJson(v));
      });
      points = arr0;
    }
    id = json['_id']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (points != null) {
      final v = points;
      final arr0 = [];
      v?.forEach((v) {
        arr0.add(v.toJson());
      });
      data['points'] = arr0;
    }
    data['_id'] = id;
    return data;
  }
}

class PressureLinesPoints {

  double? x;
  double? y;
  String? id;

  PressureLinesPoints({
    this.x,
    this.y,
    this.id,
  });
  PressureLinesPoints.fromJson(Map<String, dynamic> json) {
    x = json['x']?.toDouble();
    y = json['y']?.toDouble();
    id = json['_id']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['x'] = x;
    data['y'] = y;
    data['_id'] = id;
    return data;
  }
}

class PressureLines {

  dynamic altitud;
  List<PressureLinesPoints>? points;
  String? id;

  PressureLines({
    this.altitud,
    this.points,
    this.id,
  });
  PressureLines.fromJson(Map<String, dynamic> json) {
    altitud = json['altitud'];
    if (json['points'] != null) {
      final v = json['points'];
      final arr0 = <PressureLinesPoints>[];
      v.forEach((v) {
        arr0.add(PressureLinesPoints.fromJson(v));
      });
      points = arr0;
    }
    id = json['_id']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['altitud'] = altitud;
    if (points != null) {
      final v = points;
      final arr0 = [];
      v?.forEach((v) {
        arr0.add(v.toJson());
      });
      data['points'] = arr0;
    }
    data['_id'] = id;
    return data;
  }
}

class Axis {

  List<double>? x;
  List<double>? yWeight;
  List<double>? yAltitud;
  String? id;

  Axis({
    this.x,
    this.yWeight,
    this.yAltitud,
    this.id,
  });
  Axis.fromJson(Map<String, dynamic> json) {
    if (json['x'] != null) {
      final v = json['x'];
      final arr0 = <double>[];
      v.forEach((v) {
        arr0.add(v.toDouble());
      });
      x = arr0;
    }
    if (json['yWeight'] != null) {
      final v = json['yWeight'];
      final arr0 = <double>[];
      v.forEach((v) {
        arr0.add(v.toDouble());
      });
      yWeight = arr0;
    }
    if (json['yAltitud'] != null) {
      final v = json['yAltitud'];
      final arr0 = <double>[];
      v.forEach((v) {
        arr0.add(v.toDouble());
      });
      yAltitud = arr0;
    }
    id = json['_id']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (x != null) {
      final v = x;
      final arr0 = [];
      v?.forEach((v) {
        arr0.add(v);
      });
      data['x'] = arr0;
    }
    if (yAltitud != null) {
      final v = yAltitud;
      final arr0 = [];
      v?.forEach((v) {
        arr0.add(v);
      });
      data['yAltitud'] = arr0;
    }
    if (yWeight != null) {
      final v = yWeight;
      final arr0 = [];
      v?.forEach((v) {
        arr0.add(v);
      });
      data['yWeight'] = arr0;
    }
    data['_id'] = id;
    return data;
  }
}

class RateOfClimbGraphic {

  String? id;
  List<String>? aircraft;
  String? title;
  String? velocity;
  Axis? axis;
  List<PressureLines>? pressureLines;
  List<WeightLines>? weightLines;
  List<ReferenceLine>? referenceLine;
  String? createdAt;
  String? updatedAt;

  RateOfClimbGraphic({
    this.id,
    this.aircraft,
    this.title,
    this.velocity,
    this.axis,
    this.pressureLines,
    this.weightLines,
    this.referenceLine,
    this.createdAt,
    this.updatedAt,
  });
  RateOfClimbGraphic.fromJson(Map<String, dynamic> json) {
    id = json['_id']?.toString();
    if (json['aircraft'] != null) {
      final v = json['aircraft'];
      final arr0 = <String>[];
      v.forEach((v) {
        arr0.add(v.toString());
      });
      aircraft = arr0;
    }
    title = json['title']?.toString();
    velocity = json['velocity']?.toString();
    axis = (json['axis'] != null) ? Axis.fromJson(json['axis']) : null;
    if (json['pressureLines'] != null) {
      final v = json['pressureLines'];
      final arr0 = <PressureLines>[];
      v.forEach((v) {
        arr0.add(PressureLines.fromJson(v));
      });
      pressureLines = arr0;
    }
    if (json['weightLines'] != null) {
      final v = json['weightLines'];
      final arr0 = <WeightLines>[];
      v.forEach((v) {
        arr0.add(WeightLines.fromJson(v));
      });
      weightLines = arr0;
    }
    if (json['referenceLine'] != null) {
      final v = json['referenceLine'];
      final arr0 = <ReferenceLine>[];
      v.forEach((v) {
        arr0.add(ReferenceLine.fromJson(v));
      });
      referenceLine = arr0;
    }
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['_id'] = id;
    if (aircraft != null) {
      final v = aircraft;
      final arr0 = [];
      v?.forEach((v) {
        arr0.add(v);
      });
      data['aircraft'] = arr0;
    }
    data['title'] = title;
    data['velocity'] = velocity;
    if (axis != null) {
      data['axis'] = axis?.toJson();
    }
    if (pressureLines != null) {
      final v = pressureLines;
      final arr0 = [];
      v?.forEach((v) {
        arr0.add(v.toJson());
      });
      data['pressureLines'] = arr0;
    }
    if (weightLines != null) {
      final v = weightLines;
      final arr0 = [];
      v?.forEach((v) {
        arr0.add(v.toJson());
      });
      data['weightLines'] = arr0;
    }
    if (referenceLine != null) {
      final v = referenceLine;
      final arr0 = [];
      v?.forEach((v) {
        arr0.add(v.toJson());
      });
      data['referenceLine'] = arr0;
    }
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    return data;
  }
}
