///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class V2TableRowData {

  int? temperature;
  String? velocityName;
  int? velocityValue;
  String? id;

  V2TableRowData({
    this.temperature,
    this.velocityName,
    this.velocityValue,
    this.id,
  });
  V2TableRowData.fromJson(Map<String, dynamic> json) {
    temperature = json['temperature']?.toInt();
    velocityName = json['velocityName']?.toString();
    velocityValue = json['velocityValue']?.toInt();
    id = json['_id']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['temperature'] = temperature;
    data['velocityName'] = velocityName;
    data['velocityValue'] = velocityValue;
    data['_id'] = id;
    return data;
  }
}

class V2TableRow {

  int? pressure;
  int? weight;
  List<V2TableRowData>? data;
  String? id;

  V2TableRow({
    this.pressure,
    this.weight,
    this.data,
    this.id,
  });
  V2TableRow.fromJson(Map<String, dynamic> json) {
    pressure = json['pressure']?.toInt();
    weight = json['weight']?.toInt();
    if (json['data'] != null) {
    final v = json['data'];
    final arr0 = <V2TableRowData>[];
    v.forEach((v) {
    arr0.add(V2TableRowData.fromJson(v));
    });
      data = arr0;
    }
    id = json['_id']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['pressure'] = pressure;
    data['weight'] = weight;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v?.forEach((v) {
        arr0.add(v.toJson());
      });
      data['data'] = arr0;
    }
    data['_id'] = id;
    return data;
  }
}

class V2TableModel {

  String? id;
  List<String>? aircraft;
  String? title;
  String? createdAt;
  String? updatedAt;
  List<V2TableRow>? rows;

  V2TableModel({
    this.id,
    this.aircraft,
    this.title,
    this.createdAt,
    this.updatedAt,
    this.rows,
  });
  V2TableModel.fromJson(Map<String, dynamic> json) {
    id = json['_id']?.toString();
    if (json['aircraft'] != null) {
    final v = json['aircraft'];
    final arr0 = <String>[];
    v.forEach((v) {
    arr0.add(v.toString());
    });
      aircraft = arr0;
    }
    title = json['title']?.toString();
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
    if (json['rows'] != null) {
      final v = json['rows'];
      final arr0 = <V2TableRow>[];
      v.forEach((v) {
        arr0.add(V2TableRow.fromJson(v));
      });
      rows = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['_id'] = id;
    if (aircraft != null) {
      final v = aircraft;
      final arr0 = [];
      v?.forEach((v) {
        arr0.add(v);
      });
      data['aircraft'] = arr0;
    }
    data['title'] = title;
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    if (rows != null) {
      final v = rows;
      final arr0 = [];
      v?.forEach((v) {
        arr0.add(v.toJson());
      });
      data['rows'] = arr0;
    }
    return data;
  }
}
