///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class VYtableRowsPressures {
/*
{
  "pressureAltitude": 0,
  "velocityValue": 150
} 
*/

  int? pressureAltitude;
  int? velocityValue;
  String? id;

  VYtableRowsPressures({
    this.pressureAltitude,
    this.velocityValue,
    this.id
  });
  VYtableRowsPressures.fromJson(Map<String, dynamic> json) {
    pressureAltitude = json['pressureAltitude']?.toInt();
    velocityValue = json['velocityValue']?.toInt();
    id = json['_id']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['pressureAltitude'] = pressureAltitude;
    data['velocityValue'] = velocityValue;
    data['_id'] = id;
    return data;
  }
}

class VYtableRows {
/*
{
  "grossWeight": 16000,
  "pressures": [
    {
      "pressureAltitude": 0,
      "velocityValue": 150
    }
  ]
} 
*/

  int? grossWeight;
  String? id;
  List<VYtableRowsPressures>? pressures;

  VYtableRows({
    this.grossWeight,
    this.pressures,
    this.id
  });
  VYtableRows.fromJson(Map<String, dynamic> json) {
    grossWeight = json['grossWeight']?.toInt();
    id = json['_id']?.toString();
  if (json['pressures'] != null) {
  final v = json['pressures'];
  final arr0 = <VYtableRowsPressures>[];
  v.forEach((v) {
  arr0.add(VYtableRowsPressures.fromJson(v));
  });
    pressures = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['grossWeight'] = grossWeight;
    data['_id'] = id;
    if (pressures != null) {
      final v = pressures;
      final arr0 = [];
  v?.forEach((v) {
  arr0.add(v.toJson());
  });
      data['pressures'] = arr0;
    }
    return data;
  }
}

class VYTableModel {
/*
{
  "_id": "666b2b3438384c67783f2dab",
  "aircraft": [
    "66090cf074d32ad66c70d769"
  ],
  "title": "VY CLIMB SPEED SCHEDULE (KIAS)",
  "rows": [
    {
      "grossWeight": 16000,
      "pressures": [
        {
          "pressureAltitude": 0,
          "velocityValue": 150
        }
      ]
    }
  ],
  "createdAt": "2024-06-13T17:24:04.676Z",
  "updatedAt": "2024-06-13T17:27:34.377Z"
} 
*/

  String? id;
  List<String>? aircraft;
  String? title;
  List<VYtableRows>? rows;
  String? createdAt;
  String? updatedAt;

  VYTableModel({
    this.id,
    this.aircraft,
    this.title,
    this.rows,
    this.createdAt,
    this.updatedAt,
  });
  VYTableModel.fromJson(Map<String, dynamic> json) {
    id = json['_id']?.toString();
  if (json['aircraft'] != null) {
  final v = json['aircraft'];
  final arr0 = <String>[];
  v.forEach((v) {
  arr0.add(v.toString());
  });
    aircraft = arr0;
    }
    title = json['title']?.toString();
  if (json['rows'] != null) {
  final v = json['rows'];
  final arr0 = <VYtableRows>[];
  v.forEach((v) {
  arr0.add(VYtableRows.fromJson(v));
  });
    rows = arr0;
    }
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['_id'] = id;
    if (aircraft != null) {
      final v = aircraft;
      final arr0 = [];
  v?.forEach((v) {
  arr0.add(v);
  });
      data['aircraft'] = arr0;
    }
    data['title'] = title;
    if (rows != null) {
      final v = rows;
      final arr0 = [];
  v?.forEach((v) {
  arr0.add(v.toJson());
  });
      data['rows'] = arr0;
    }
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    return data;
  }
}
